# Generated by Django 5.1.15 on 2026-05-25 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='install_duration_seconds',
            field=models.IntegerField(blank=True, help_text='Duración neta de la instalación', null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='install_end_time',
            field=models.DateTimeField(blank=True, help_text='Cuando finalizó la instalación', null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='install_start_time',
            field=models.DateTimeField(blank=True, help_text="Cuando el técnico presionó 'Start Installation'", null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='installation_log',
            field=models.JSONField(blank=True, default=list, help_text='Array de JSON con la bitácora: [{id, time, text, photoUrl}]', null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('activo', 'Activo'), ('instalado', 'Instalado'), ('reparado', 'Reparado'), ('reparacion', 'En reparación'), ('danado', 'Dañado')], default='activo', max_length=20),
        ),
    ]
